### ISSUE TITLE
Support for primary key with datatype String

### ISSUE THREAD

**Issue by HaakonSonsteby** [jhannes/fluent-jdbc#12]
Currently only Long is supported: https://github.com/jhannes/fluent-jdbc/blob/b73affcd9abb3b87ac95d7a7827b3a1986a13a6e/src/main/java/org/fluentjdbc/DbTableContext.java#L67

**Comment by markkulube** [comment]
@HaakonSonsteby I could work on this.

Is this possible to flesh this out a bit more.

Are we really only looking method overloading of both method i.e the one you reference above and

https://github.com/jhannes/fluent-jdbc/blob/b73affcd9abb3b87ac95d7a7827b3a1986a13a6e/src/main/java/org/fluentjdbc/DatabaseTable.java#L37

My background:
I have completed a few first time issues above and over my other work/school programming pursuits in different frameworks/languages.

I think this looks like a good next step for me with a bit more details and/or direction especially because Java is my favorite language / strong suit.
